spring:
  datasource:
    url: jdbc:h2:mem:asistec;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080


logging:
  level:
    com.innovaschools: INFO
